AllCops:
  Exclude:
    - db/**/*
    - bin/**

SignalException:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false
