web:
  build: .
  command: bundle exec rails server -b 0.0.0.0 -p 4000
  links:
    - redis
    - mongo
  ports:
    - '4000:4000'
  volumes:
    - .:/home/app
  environment:
    RAILS_ENV: development

redis:
  image: redis

mongo:
  image: mongo
